# This workflow will do a clean install of dependencies and run webpack build.

name: Run Webpack Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"
      - run: npm run geojson
