# This workflow will do a clean install of dependencies and run webpack build.

name: Create GeoJSON File

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  create_geojson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"
      - run: npm run geojson
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Automatically Updated GeoJSON File'
          add: '*.geojson --force'
