# This workflow will do a clean install of dependencies and run tests.

name: Tests

on: [push, pull_request]

jobs:
  create_geojson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://npm.pkg.github.com"
      - name: Install modules
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
      - name: Run tests
        run: npm run test
